---
- hosts: webservers
  gather_facts: yes
  tasks:
   - name: Update cache
     become: yes
     apt:
      update_cache: yes
   - name: Install php-fpm version 7.4
     become: yes
     apt:
      name: php7.4-fpm
      state: present
   - name: check if nginx is installed
     become: yes
     apt:
      name: nginx
      state: latest
   - name: initiate nginx
     become: yes
     service:
         name: nginx
         state: started
   - name: Copy php file
     become: yes
     copy:
       src: index.php
       dest: /var/www/html/
   - name: Change the template file
     become: yes
     template:
       src: nginx.conf.j2
       dest: /etc/nginx/sites-available/default
   - name: Enable the configuration file
     become: yes
     file:
       src: /etc/nginx/sites-available/default
       dest: /etc/nginx/sites-enabled/default
       state: link
   - name: Restart the Servers
     become: yes
     service:
          name: nginx
          state: restarted

- hosts: haproxy
  gather_facts: yes
  become: yes
  tasks:
   - name: Update cache in Haproxy
     apt:
      update_cache: yes
   - name: Install haproxy
     become: yes
     apt:
      name: haproxy
      state: present
   - name: Update config file for HAproxy
     template:
      src: haproxy.cfg.j2
      dest: /etc/haproxy/haproxy.cfg
   - name: Restart HAProxy
     service:
       name: haproxy
       state: restarted
